version: 1
accounts:
  - name: user1
    coins: ["1000token", "100000000stake", "10000nametoken"]
  - name: user2
    coins: ["500token", "1000nametoken"]
validator:
  name: user1
  staked: "100000000stake"
