name: Build & Deploy Docs
# This job builds and deploys documentation to github pages.
# It runs on every push to master.
# Note: A git update is required by the checkout action to enable submodule checkout via http(s)
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:14
    steps:
      - name: Prepare build container âš™ï¸
        run: |
          apt-key adv --recv-keys --keyserver keyserver.ubuntu.com A1715D88E1DF1F24
          apt update
          apt install -y rsync libpcre2-8-0
          wget http://ppa.launchpad.net/git-core/ppa/ubuntu/pool/main/g/git/git-man_2.18.0-0ppa1~ubuntu17.10.1_all.deb -O /tmp/git-man
          wget http://ppa.launchpad.net/git-core/ppa/ubuntu/pool/main/g/git/git_2.18.0-0ppa1~ubuntu17.10.1_amd64.deb -O /tmp/git
          dpkg -i /tmp/git-man
          dpkg -i /tmp/git

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Install and Build ğŸ”§
        run: make build-website

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .vuepress/dist
