name: Documentation
# This job builds and deploys documentation to github pages.
# It runs on every push to master.
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine #etlify/build:xenial
    steps:
      - name: Prepare build container âš™ï¸
        run: |
          apk add rsync git make

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Install and Build ğŸ”§
        run: make build-website

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .vuepress/dist
