name: PoFE
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.15
      - uses: actions/checkout@v2.3.4
      - name: Test Build
        run: |
          cd proof-of-file-existence/pofe && go get ./... && make install
