name: Verify valid config.js
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  verify-config-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: âœ… Verify valid config.js
        run: |
          npm ci
          npm run check-config
